#!/bin/bash
# Render the Mosquitto config + password file on disk.
#
# Two calling conventions:
#
# 1. Docker (mosquitto-init service in compose):
#    - MQTT_USER and MQTT_PASSWORD are env vars in the container
#      (set by compose's env_file directive)
#    - Pass the data dir as $1: bash /render-mqtt-passwd.sh /mosquitto/data
#
# 2. Host (legacy podman render-mosquitto-passwd.service):
#    - MQTT_USER and MQTT_PASSWORD are in $ENV_FILE
#    - bash /render-mqtt-passwd.sh /srv/sv02/mosquitto/data /srv/sv02/secrets/mosquitto.env
#
# Run as root — the data dir may be owned by a different uid
# (e.g. uid 1883 from the eclipse-mosquitto user), and we need
# to chown it.
set -euo pipefail
# Self-execute in case git reset the mode bit. (Idempotent.)
chmod +x "$0" 2>/dev/null || true

CONFDIR="${1:-/srv/sv02/mosquitto/data}"
ENV_FILE="${2:-}"

# Sanity check: either we have env vars (docker) or a file (host)
if [[ -z "$ENV_FILE" ]]; then
    # Docker mode: rely on env vars
    : "${MQTT_USER:?MQTT_USER not set in container env}"
    : "${MQTT_PASSWORD:?MQTT_PASSWORD not set in container env}"
else
    # Host mode: source from file
    [[ -r "$ENV_FILE" ]] || { echo "[render-mqtt-passwd] FATAL: cannot read $ENV_FILE" >&2; exit 1; }
    set -a
    # shellcheck disable=SC1090
    source <(grep -v '^[[:space:]]*#' "$ENV_FILE" | grep -v '^[[:space:]]*$')
    set +a
    : "${MQTT_USER:?MQTT_USER not set in $ENV_FILE}"
    : "${MQTT_PASSWORD:?MQTT_PASSWORD not set in $ENV_FILE}"
fi

# Ensure the dir exists. If it's owned by a different user
# (e.g., uid 1883 from a previous mosquitto container run),
# chown it to us so subsequent chmods work.
if [[ -d "$CONFDIR" ]]; then
    if [[ -O "$CONFDIR" ]]; then
        :
    else
        chown "$(id -u):$(id -g)" "$CONFDIR" 2>/dev/null || {
            echo "[render-mqtt-passwd] WARNING: cannot chown $CONFDIR"
        }
    fi
    chmod 755 "$CONFDIR" 2>/dev/null || true
else
    install -d -m 755 "$CONFDIR"
fi

# Load env vars (KEY=value lines, # comments)
set -a
# shellcheck disable=SC1090
source <(grep -v '^[[:space:]]*#' "$ENV_FILE" | grep -v '^[[:space:]]*$')
set +a

: "${MQTT_USER:?MQTT_USER not set in $ENV_FILE}"
: "${MQTT_PASSWORD:?MQTT_PASSWORD not set in $ENV_FILE}"

# Render the mosquitto.conf
cat > "$CONFDIR/mosquitto.conf" << EOF
# Generated by render-mqtt-passwd.sh
# Paths are INSIDE the container — /mosquitto/data is bind-mounted
# from /srv/sv02/mosquitto/data on the host.
listener 1883
allow_anonymous false
password_file /mosquitto/data/passwd
persistence false
log_dest stdout
log_type all
connection_messages true
EOF
chmod 644 "$CONFDIR/mosquitto.conf" 2>/dev/null || true

# Render the passwd file. Two strategies:
#
# 1. Docker: we're running inside the eclipse-mosquitto image,
#    which has /usr/sbin/mosquitto_passwd. Just run it.
#
# 2. Host (legacy podman): run it via a one-shot container.
#
# We detect #1 by checking for the binary on PATH.
if command -v mosquitto_passwd >/dev/null 2>&1; then
    mosquitto_passwd -b -c "$CONFDIR/passwd" "$MQTT_USER" "$MQTT_PASSWORD"
else
    # Host context: use a one-shot podman container.
    podman run --rm --network=none \
        docker.io/library/eclipse-mosquitto:2.0 \
        mosquitto_passwd -b -c /dev/stdout "$MQTT_USER" "$MQTT_PASSWORD" \
        > "$CONFDIR/passwd"
fi
chmod 644 "$CONFDIR/passwd" 2>/dev/null || true

echo "[render-mqtt-passwd] rendered $CONFDIR/mosquitto.conf and passwd for user $MQTT_USER"
