#!/bin/bash
# Render the Mosquitto config + password file on disk.
# Called by render-mosquitto-passwd.service (a one-shot unit).
#
# Reads MQTT_USER and MQTT_PASSWORD from /srv/sv02/secrets/mosquitto.env,
# writes /srv/sv02/mosquitto/data/mosquitto.conf and passwd.
#
# The passwd is hashed with a one-shot `podman run` because the host
# doesn't have mosquitto_passwd installed (and we don't want to install
# it just for this).
#
# Run as root (the service invokes via sudo) — the data dir may be
# owned by a namespaced uid from a previous podman run, and we need
# to chown it.
set -euo pipefail
# Self-execute in case git reset the mode bit. (Idempotent.)
chmod +x "$0" 2>/dev/null || true

ENV_FILE=/srv/sv02/secrets/mosquitto.env
CONFDIR=/srv/sv02/mosquitto/data

# Sanity check
[[ -r "$ENV_FILE" ]] || { echo "[render-mqtt-passwd] FATAL: cannot read $ENV_FILE" >&2; exit 1; }

# Ensure the dir exists. If it's owned by a different user
# (e.g., a previous podman run created it with a namespaced uid),
# chown it to us so subsequent chmods work.
if [[ -d "$CONFDIR" ]]; then
    if [[ -O "$CONFDIR" ]]; then
        # We own it
        :
    else
        # Owned by someone else (often a namespaced uid from a
        # previous podman run). Try to take ownership.
        chown "$(id -u):$(id -g)" "$CONFDIR" 2>/dev/null || {
            echo "[render-mqtt-passwd] WARNING: cannot chown $CONFDIR (will retry on next render)"
        }
    fi
    chmod 755 "$CONFDIR" 2>/dev/null || true
else
    install -d -m 755 "$CONFDIR"
fi

# Load env vars (KEY=value lines, # comments)
set -a
# shellcheck disable=SC1090
. "$ENV_FILE"
set +a
: "${MQTT_USER:?MQTT_USER not set in $ENV_FILE}"
: "${MQTT_PASSWORD:?MQTT_PASSWORD not set in $ENV_FILE}"

# Render the mosquitto.conf
cat > "$CONFDIR/mosquitto.conf" << EOF
# Generated by render-mqtt-passwd.sh
# The paths here are INSIDE the container — /mosquitto/data is
# bind-mounted from /srv/sv02/mosquitto/data on the host.
listener 1883
allow_anonymous false
password_file /mosquitto/data/passwd
persistence false
log_dest stdout
log_type all
connection_messages true
EOF
chmod 644 "$CONFDIR/mosquitto.conf" 2>/dev/null || true
# passwd file is 644 so the mosquitto container user (uid 1883) can read it
# (it doesn't need to write). The hash itself doesn't grant auth.
chmod 644 "$CONFDIR/passwd" 2>/dev/null || true

# Render the passwd file by running mosquitto_passwd in a throwaway
# container. The passwd format is "user:password_hash" where the hash
# is bcrypt (libmosquitto's default).
rm -f "$CONFDIR/passwd"
podman run --rm \
    --network=none \
    -v "$CONFDIR:/work" \
    --entrypoint /bin/sh \
    docker.io/library/eclipse-mosquitto:2.0 \
    -c "/usr/bin/mosquitto_passwd -b -c /work/passwd '$MQTT_USER' '$MQTT_PASSWORD'"
chmod 600 "$CONFDIR/passwd"
chown rkruit:rkruit "$CONFDIR/passwd"

echo "[render-mqtt-passwd] rendered $CONFDIR/mosquitto.conf and passwd for user $MQTT_USER"
