---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: iproyalpawns-credentials
  namespace: iproyalpawns
spec:
  encryptedData:
    password: AgCrKx2/jXwf0sEublfNeCF2tjJHZLmo5VvU5i4yAQLTo0yrj4AXaneSPakJXYSGaRbQOc5h0sDkes8jLqjF7qSW+Z1rL+zXSA2UUwP0k7tfcktkmXw8SH+prJ6JFIHxyw2StQc4q4+KjoUFmoj3JcyvDjjXW2NjKOcKqA8kgGjA1PeIm/hfF152e2buBfHEwKbnlQmRS9o9h4pBzq7SVn56PypZqElJMDJ1Hj5rt7CCNyMRgxXIy5ao0wU0CGYJdyCAXBKtYzs38gc6ZqHT8E5JUQ4xBfqZnXacsRjJO5r6RcjckE3fkUMlqlAqmmuu+HD2dq6xt5tJjqu8ecl31WeH+AanNEnNGU6n9O0vFa1UBIyuOcFD1UWszCfli1OKDOg7CBLU+iDYj65Daf7KZmMLu68rQXo31CPS9gOqxa9Pku/liTSdckGsn4wpt3hdFoXOqkLTepHA/XwApYsjHVt+mo0Ng8fDs6t84Z3Kc3oTW6xFMJBGZ6WXVn5qT6tVzleUrFbE+8b1DPBYRnbqvOCv9y7vZSYi+A+VJbGZ1eGeGRQZ7pG/tuNsZR+tn7/qAq1CVynZA0X4I6LYZh2dPkXEq6X7KZsHk9vueH4ifiMwfCjJjdqj7NM6yTQFQGTbPjJOvPWps9SpMfWOme9gaSJWnXMALTAngBzOLsBn/Nv5RwUekJ86DRYluvx74sEew7QuQy+XkyKt0raxZ055Dw==
  template:
    metadata:
      creationTimestamp: null
      name: iproyalpawns-credentials
      namespace: iproyalpawns
