apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: default
spec:
  project: default
  source:
    repoURL: https://github.com/RKruit/k3s-gitops.git
    targetRevision: main
    path: base/traefik
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
