apiVersion: apps/v1
kind: Deployment
metadata:
  name: uptime-kuma
  namespace: uptime-kuma
  labels:
    app: uptime-kuma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uptime-kuma
  template:
    metadata:
      labels:
        app: uptime-kuma
    spec:
      containers:
        - name: uptime-kuma
          image: louislam/uptime-kuma:2
          ports:
            - containerPort: 3001
              name: http
          env:
            - name: PORT
              value: "3001"
          volumeMounts:
            - name: data
              mountPath: /app/data
          resources:
            limits:
              memory: 512Mi
              cpu: 500m
            requests:
              memory: 128Mi
              cpu: 50m
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: uptime-kuma-data
