apiVersion: v1
kind: PersistentVolume
metadata:
  name: asa-server-data
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  claimRef:
    namespace: asa-server
    name: asa-server-data
  hostPath:
    path: /opt/asa-server-live
    type: DirectoryOrCreate
