apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: asa-server-data
  namespace: asa-server
  labels:
    app.kubernetes.io/name: asa-server
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: asa-server-data
  resources:
    requests:
      storage: 100Gi
