apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: asa-server-data
  namespace: asa-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: nfs-client
