apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: asa-server-secret
  namespace: asa-server
spec:
  encryptedData:
    admin-password: AgBcN43CLA22PZo/QhMpww2bv7Z0N1kvMj1hMrHuw1iMrL2OFzC/VEQtDiS4kov0tQWTJcEXTBDZF+c8dFpF/kpF4iAixjRs8ftKPNtn3T2iGkjEjU7I0csEyX71L04Zl3CCYWv2Ze7Rchv7ipCFvEO3JHVkuG0ZD4hqx5odvI/q3nvx6MGvqTTC5DKnqb4aq77sFavPl5AcBst3eVH8VxyEQQ5YBF9nr7qRYll6QFf7piDLGAquT5iOWVUpe/jCoTvL5K1bZ6dWQwVPjXWRxuLDYzSZYFf4HAySmCo1qxVkJMrUtwobO4W1tcfdQBwvV5+UoNoounIcFzjb2sBgGJw8Jrl+77HvKoMOQLxMqJ0+sg2aEVZYuyiIzmPWKNCjwj7lH7E4wH2WCgdvtBF6yO5S8saMLqkHW5f777ReHlM9BEQzkf/6by+2/GOlGVzJ8u3Pfs8esIyGJCbgZxLjWy54l9vsOh0FCTEgAAWfF+xUNeAPj6dGM/KEGUXJ+Zd/hUxoBbsQDd1p+4zLla/ExArN2IpYcf+Ua8nZuB/+b1a9ovq8Vcp5d1VwbmFswHzUMIdac5QNKaugpj+t/X3oLXG2aQUY3vDTLZEtxA2lwnlnchvqIZJ+0UeSCvAKeRSEB94nvWS9OgbgEhPc/ag9mwwt1zF2h3IsSYYyJx+47wE9QrlbFIOgLvy6BkX5W+kZ8xrNMBemJnCyXEPU5VaElQ==
    server-password: AgAf1rRXK8O/oTUVY8lXJFIzwtD5khi7LPm+19lt/eYQxUIOHIuptuEtBX8SY3fLY2COk+XXHVBbEdBmEJK7ws7RUBUcn2oBzPQ8ET3qWGLqvm2bvWeBWIxkY3JoJZwZ3mQUtfWfp0jjtXW7Rnh+DWOEDTuFKUGQ2l2zidudhU8wqtBffAyXQwBGwI7PnXfxST4XVTcgYsm1U8u1KO+Xq09jzGmFLJAnMXkYB1DOlqPv+urX96QBp6Ef4MKp8dryFGLr6XNhK0r2cXbrzK7JDbGrHPFBpUB7KKWl2cECCgWEuKiGfUift0T1A0dBhzslXUiTm/ZYU8Rm8Tg8VEux8HG9WHALW6hLHryFXh6EigDnLV7EcdNu1AShlDefBQ0vBTCpnLYt7G8kXDO02MAXUZr9ZJDbkngqBH0G/TuceLNBlq3brw1/8gQBbAvnBOB3vh4+PmAJ6B4j6B+Cc+ie3YA6N5rSPC17hyb9dZDqGjLLgcV+vyVZyYJH2FMB/brmCRooiMFcwN9HPIgvlWgEic59tqHRBrFbVDp+/wieFGgRVye84EpWKK9Ctv+BPvU7x5gGUoYT2Og2GUmc/384J59PsmpfFNr4zpYvJd0SKY3jJ7qrkQC58sCbVDPUMBVPst9RtaAqFPoHFwxlxCxJZqrIDFKRkcIbLHV1C+bUWf2glwaPT8sMYiXrJ/u3wXAm8tt3G7gORQnjc/45/adXaw==
  template:
    metadata:
      name: asa-server-secret
      namespace: asa-server
    type: Opaque
