apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: asa-server-secret
  namespace: asa-server
spec:
  encryptedData:
    admin-password: AgBthCkDRrNROsa7uysm/pBQctJCid5utABJL2ebHZrStEvYVK2np03W0WvV5OYjWYoq8ox3ONRhghQ2r72+Yjzb9qAcCZhuDHeYaz8/MHRLOnSJzUWpimRzJJ1+1dr02pTHUH3Lo8Wo7oqOdU4aXGL8h+sHA8D0XGdPgsNJGw9Tqy1oV1bIQtSkEqXLmfeLmQGbD1p13QeX9i8+ZDnKvRQbVB2Fea/sIgRZEoMpEb74ZdpY0s55Akl4zAO0RSqSxgjt0MDYFuMgQa1hoXTJLXFJGphf+fEaBwtan04Fnirsc/IGlup761NflL4Wcpq5+tGOyNVEaS7fjurh1dZJOBBhMMRRVgvt1a/0wcS6zjjF4fExvApCY6U/AuaQlJYrEhl7Jzc88myy6IkMxZqkFt3eTDnRJKyTYCwGFJRMiipYJYBsuD5Z8WFJ+W3xyzfqSTKkVUmn+FOEBvU7+lTQ+ASvDv/0nsJ+6wr2q6qdpS1ljkJlHMKHkFW3/dJ9lowjzQXNP0pdjw1Qvpv4vqoKZUruJROqEq4iTZfuCAJRbFa73OzpcE7mZEMSCoiN4xC6AZ1BAA1vnthukuOImUqUSilyvn0RvK+C/OBQBigOOmfO58s1mJ8SGf4rX1X5T1fmeRU6EUmxrWhQUTCusLlxYFhl447cwYCKao2pmy93xRP/wY8BNzTbH4sdZNgaJyp0MkReRsCiTSqcpOcD6TfX4g==
    server-password: AgAEZXHVQCDY04fNzsHnLPIPZSiIAMegcS1T1heceNl9LBPVZS55wdOsGKdALTCta1F4Etgoy0SmLZhWvhf7fcLUDOurTidN9Q/f+WXx3K2KZRVkH6crF2/vHega2RGVEfn8su85b8rLVrDj1iID1Gat+8sT8RutWX4qQrOuDeQCN76e+xN6W3A8YVjxF2cUbGOQfYH3et1lE1hqc/N0ap4K8+iH8ZkfV2U4JC5CxYE+5PFXdIx6JmANq12o0IGHH626k6Oob6hrBOd4w60EepJ53/VNKvTKF19ArW3rz/NuJu2eI1c1nNnVCbNpkH4IGLTUPUKNh/2OKKAoGYtPkXwB1VawYbI6OW/jbX5IGTyf+IovbOUNjH7V9mngZstsV2+bwlIpPP3I07EBU2gfta5jDZ2Ms0fiI/f6g439AZSSbAjYEfrwl+9CSySxCJglhdLrThLGw91i3isCfG4JPiId1Jj6MTWhbYykF0cLxbEwqLRkFoPaMPoaekrMTgWYGWufOpK94LVobN2sFAqaXEElV3sz+8mtOrlmU3MKqTRe1xUy2H2Laahebf71VwNzbNFWxeczFY/Cqed/+1KNtkS5O5NPkSoZjIaCuYyunMCG/WTntpO+NofXHxjTy+AAgVIxRMqTVuI9WSXv4746dluCUPIbtGON3aVE1uC5E5GcF+bGma+n0gERo7yG6R4zg9Z8yEuiNctjgTYkLhPmeg==
  template:
    metadata:
      name: asa-server-secret
      namespace: asa-server
    type: Opaque
