apiVersion: v1
kind: Secret
metadata:
  name: asa-server-secret
  namespace: asa-server
type: Opaque
stringData:
  admin-password: "REPLACE_WITH_YOUR_ADMIN_PASSWORD"
  server-password: "REPLACE_WITH_YOUR_SERVER_PASSWORD"
