apiVersion: v1
kind: Service
metadata:
  name: asa-server
  namespace: asa-server
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: asa-server
  ports:
  - name: game-tcp
    port: 7777
    targetPort: 7777
    protocol: TCP
  - name: game-udp
    port: 7777
    targetPort: 7777
    protocol: UDP
  - name: rcon
    port: 27020
    targetPort: 27020
    protocol: TCP
