apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: asa-server
  namespace: asa-server
  labels:
    app.kubernetes.io/instance: asa-server
spec:
  replicas: 1
  serviceName: asa-server
  selector:
    matchLabels:
      app.kubernetes.io/name: asa-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: asa-server
    spec:
      nodeSelector:
        kubernetes.io/hostname: sv01
      containers:
      - name: asa-server
        image: docker.io/acekorneya/asa_server:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 7777
          name: game
          protocol: TCP
        - containerPort: 7777
          name: game-udp
          protocol: UDP
        - containerPort: 27020
          name: rcon
          protocol: TCP
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: BATTLEEYE
          value: "FALSE"
        - name: RCON_ENABLED
          value: "TRUE"
        - name: DISPLAY_POK_MONITOR_MESSAGE
          value: "FALSE"
        - name: UPDATE_SERVER
          value: "TRUE"
        - name: CHECK_FOR_UPDATE_INTERVAL
          value: "24"
        - name: UPDATE_WINDOW_MINIMUM_TIME
          value: "12:00 AM"
        - name: UPDATE_WINDOW_MAXIMUM_TIME
          value: "11:59 PM"
        - name: RESTART_NOTICE_MINUTES
          value: "30"
        - name: ENABLE_MOTD
          value: "FALSE"
        - name: MAP_NAME
          value: TheIsland
        - name: SESSION_NAME
          value: TokkieTown
        - name: SERVER_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: admin-password
              name: asa-server-secret
        - name: SERVER_PASSWORD
          valueFrom:
            secretKeyRef:
              key: server-password
              name: asa-server-secret
        - name: ASA_PORT
          value: "7777"
        - name: RCON_PORT
          value: "27020"
        - name: MAX_PLAYERS
          value: "70"
        - name: CLUSTER_ID
          value: cluster
        - name: MOD_IDS
          value: ""
        - name: CUSTOM_SERVER_ARGS
          value: ""
        - name: DISABLE_POK_MONITOR
          value: "TRUE"
        resources:
          requests:
            cpu: 500m
            memory: 8Gi
          limits:
            cpu: "4"
            memory: 16Gi
        securityContext:
          privileged: true
        volumeMounts:
        - name: data
          mountPath: /usr/games/.wine/drive_c/POK/Steam/steamapps/common
        - name: steam-temp
          mountPath: /usr/games/.wine/drive_c/POK/Steam/steamapps/downloading
        - name: steam-temp
          mountPath: /usr/games/.wine/drive_c/POK/Steam/steamapps/temp
        startupProbe:
          exec:
            command:
            - pgrep
            - -f
            - ArkAscended
          periodSeconds: 10
          failureThreshold: 180
        livenessProbe:
          exec:
            command:
            - pgrep
            - -f
            - ArkAscended
          periodSeconds: 60
          failureThreshold: 3
          initialDelaySeconds: 300
        readinessProbe:
          exec:
            command:
            - pgrep
            - -f
            - ArkAscended
          periodSeconds: 30
          failureThreshold: 5
          initialDelaySeconds: 300
      volumes:
      - name: data
        hostPath:
          path: /opt/asa-server-data
          type: DirectoryOrCreate
      - name: steam-temp
        emptyDir:
          sizeLimit: 20Gi
