apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: signoz-signoz-pvc
  namespace: signoz
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: nfs