---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: honeygain-credentials
  namespace: earn
spec:
  encryptedData:
    password: AgCz81vEXEj0xEcFrBD96H0FeQAKpYYLqB645JI3TxPKqcARrLXMejrOAwUUCX/slGQiHyGDqNeseQqxMIFHMOqGnae8mesblvDVSaa3iNQXnI+KU5P10MMCOCBXLp4FFmRH4RKg0YEb14etxqJyqD716yAnHuUiNOKdDJjLysi80GMLGSF4MJYA8BffJLlzZYXJ8OYU10nuQwZcsCNEq4HNBMgLzUd2wijZtQdNm/EZ+gVNB7rmGtzFcv/A32YHJ94+VrySHolcOI9YbJI7LLwJ/0SNvb5HoAnS4OnBgYF4zjYv+I/GUp8g6Ek7uclVBm/a8Mk5FHWBu2fioX5mIvo/PXEDJcI6NZqU4lAFbRq7IJ06f6J7jx2Utg+iIAKimO1ETC0Xg8Ll3U08x8oQDMz8NsExjbDEUOOENFufzVCiemtF4kDb1t1ftSzHt7PrJXxxNIcr7vbtPW92J7ZeWsADjozMlU/cL6mbEOS2ezAmUh9liI8U+knk/NdHUCZAk57O6QAGT2wGrMb89KwfGRQgaFeMlA0k8eky264JI/6oRE9l2aGI7TQ0MWjckyBmOPV4G3RSwso05FG6OOzDIXuFU80O1+o1pPrQnUqRR8PRNdi2t6HkQ3QafbkTdnbPQ67o/13qzElEur8NstXzWKd2xJzcAZRhzR+TzemRo0bcm7nk6leIHgTD7dopDXQiogwFvfv27tmed0Vj
  template:
    metadata:
      name: honeygain-credentials
      namespace: earn
    type: Opaque
