apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sealed-secrets

resources:
  - namespace.yaml

helmCharts:
  - name: sealed-secrets
    repo: https://bitnami-labs.github.io/sealed-secrets/
    version: "v0.27.1"
    releaseName: sealed-secrets
    namespace: sealed-secrets
    values: |
      controller:
        # Use a persistent volume for the encryption keys if you want
        # persistence:
          # enabled: true
          # storageclass: "nfs"
          # size: 1Gi
