apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: passive-income-data
  namespace: passive-income
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 1Gi