---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: honeygain-creds
  namespace: passive-income
spec:
  encryptedData:
    auth.json: AgCRtdGYACqLvpNS2dsmjopt2A81C3nOpQxTaFxsfyMm5M6bhrZnOe7J8CqP2gJSMiah3SLl+1RrfcTnxh79Y5hBMm4OPxJGDoJAs5PLPaU8vs97J/59Fihe6RqYmqAX1PAFE4Su9gXhRXYyvl9yNUhzNHR3fcOXVUVSgVRRw8HO1n8aeUREsfZQPd0N5F6O0EDXxMub/Orb2YfTySqCya9+VZ3fzplVlwfdE5UzrfhX/tEn7pua90RdKumM6ym9QMGLUk2Tm3wcOgzoD3qqWoTJan4CgXizee9dV8WmR3NtqYpOPQCbO21uTFy8xlfzVEQAzp3GRJAzRaa/QXff20/fw25IZzmK4+e+9cNRm447Aw7R8Ueigeb6SIWG6ICjPLDtSd6HtX212BM2jabj2pUM2rUk1Mpe52iBbUUVp1WRuEkzzhp0UWvFD6T6ribyTGrZi73a884ftXi+5MmxkGHNwBme2NFh9d4ndXILRK8LZbLzzWekqZ+/dimU/p7VAX1gkMZ2pMipELOEBIf/hawOH6tNMSPCdO6V5VYAhKbraeyNKRvFZ7QrkUNpRtFlDmPi+JI2vA4Kod+FjfbNAo2ZLSaCpO6pK0ucSz1tzYv/rv5uJa5vtwgDv122/Od5LtTuP4/OrXvU5ZWVSsyFdBbp/1oesJRoq1yckG5N97EL2zMXmbVA8wTDflNMal57WsMvGWyr1TekqmOSPpw8Mxq+0yhDWlcCAuDML2ur8McAIIsjg3yFE4Rk7u4ozP9jqqzI1WN3tbI=
  template:
    metadata:
      creationTimestamp: null
      name: honeygain-creds
      namespace: passive-income
