---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authentik-secrets
  namespace: authentik
spec:
  encryptedData:
    AUTHENTIK_POSTGRESQL__PASSWORD: AgC8zDA/DrfVht8uRYqq5IQ04LvfsNdXM72+6Is4fLZVHiN5C6KEJB9MOf5wJUBRWXSYVlPogDhqKoc/5mDXRZDzJmUMS98YKwl3FUOHbo/sReudU9ZpNIpcE+pzrlx8NH3ubcA1JvH6O/YWPmIV6fubUM1IIaaGMm9ewAARVxoRlv7vmFWOtud/JMFI55HnwGTTxB/xuG2BC92bYSGqYdHwTLyPpkdFi3qKx9RGsubgRfCZP6+tmM96VLUY8JLKXOJwvO6MgQJ9iQM1mxgiNv2gBRPv2AWJXyYIYnai3IVLa7xyikap3PA6m+fO7poygxTJqWDVwrr3f13O2bKzncqH53TqrnRp7115vYUnbbsnih7wAUaMYtqPlSHNruVEvsgrCfQ2lJS5s0E+RTF3z09zWWH0E2Zpllxynr2C2E4fRaN8YORy2EtBlcOiw4LhxDMQmUQFdzYS1/pw3jjPY4B04RM2X83nvcBam0/N00xWL+mi1/CtPUGnTbaQLAin/sgRb3KVO47wpOjbvVyrneeO2wlywKaHvnMI+fhcY/F0p3zlexcaIuHlzSAy30RwLifQxxoViKB+ODY/YZbULmR7SrRf+Rt4X8rmbh2wEuOP9f6e5DJKnZOMvXb/ikjQDp6rOngSRjJh9ddUMoavRikZAm5h1qf6iu/gx/5IMN2p+nCSbWxfuTYRrxlfbJMCtrNjbNiusaG9ZRzwWE2zGH9VES/me23LiQuPrkG3iBcoGA==
    AUTHENTIK_SECRET_KEY: AgCD09WozVPgY857vAwoVxg2GuhNWNvBrEA+bmxhbSk1bsv0jczCwp3xqtz+kFqJbhTpe153xg0zwg+egtumHpCSr3Sc9zjZEBXPioSdjNB92NA3rVlUc9zKuHzrR61O9GMCC23G7KIddOO5W5l1O8Yt3woCsQrUeaJjritynbVRBQLqISMJotepmhJ90e0DNoPRqVwhNffU2kfrzGEaFpahZPcium5cEafJzV8RTyj3B4LlwPl0aTWFF2xWYqp3rYRTe4vBREToYm5tfF4Z+DmI5+i3ukGMPUfbMu5OzA/nqGaXwaOLOZcg2ypFk4SDneM5NyEmKDYU93TVFcXkmXHNODXop5a3uNRdJJ4DVylNi5b/ODvipzKdaZDnioTrZn25cSxL2KwGcqywfuAA+MMXz5PNdEDsD1NHJ/PAyGZ5g7Sihgk0Co9/N1To994EmKJHugK0WZSQHRxO2F8nep+Q8nvcUtyFSLC5KPsEYuKIglR2JAKgGrm9a4RUO/360/JvplhYickcpknqv7JU9zmuIAgamio1afWsv0NhJyG3D5Abepl2L3klQ0qzO5XUIXKzewMPUkhzp1NxDJAfqqaodoxPqUPJiVLJi44sTStCH474VzyzZyd5MFIiEcRoT5Cxm075XrRCPECC9ssUdDaFHbHWWvn8X5pJHu4kwkByDx4mv3vbpoj9S2wMMikZ2EkWnxwF4LEKOxlD/aDjVRScZnA977f0gDnAUgodLDb+0PH7yvxefPrVOEUvUIiECw==
  template:
    metadata:
      creationTimestamp: null
      name: authentik-secrets
      namespace: authentik
    type: Opaque
