apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openbao-http-redirect
  namespace: openbao
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: openbao-https-redirect@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: openbao.oostrandpark.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: openbao
                port:
                  number: 8200
