apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: openbao
spec:
  provider:
    vault:
      server: "http://192.168.1.10:30820"
      path: secret
      auth:
        tokenSecretRef:
          name: openbao-token
          namespace: external-secrets
          key: token
