apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hermes-webui-tls
  namespace: hermes-webui
spec:
  dnsNames:
    - webui.oostrandpark.com
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: hermes-webui-tls