apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hermes-webui-secret
  namespace: hermes-webui
spec:
  encryptedData:
    HERMES_WEBUI_PASSWORD: AgBncAQVobZYgZxkdPmXxghD3Oh0m7YvLTTKUGQQ4Ydt/nrZZK9dt+nsb1NKQIEIbbY0JBFhDD5RY3mv9L2qyTpl/MGJhE+ZF0tQLXCo4uoa6i7eFXSzD3SetA3nCKyw+/lTLNR/1CYtwBWbKOVF7/6J0uhdK+tJQBTTSfnL0mo0VPoqepuhRPVWIFIu763ahjmYJ5IqX/1MTth+kV5tAvi1ym+E4dSYng7eNYVrBF4YSeJkld9szqPmb7hLM4CeOcADR6XKZGvAcUXk7hn/Nrtm9A7zdChJbaSrigjGY2j1G/cpfmqT/IFuVliqdyBoE3onNK0QN7Yc4KA3+Wj7eoRTwEFCsiLvc2LT1RweBOiBpWnyMlDWvenP3oywWV377cErM2V6E02mwiJSmK4R3FOyh1Y7Her6Js5TclpGsB2nqBKBXVpS6/SxikXR4ZNITKwpeBNCrWTWdFrudjJRCprZQppDRbV5fvjfctmzoNLuuAxlm52B4fFyZ9U0+G6xLFRC/gf+igUYx8sJQjmiwNOHhVS+9CgjXFXLj40CgOksl1xds5b0/f67ng5xB8tu8E3nmnOrRqkTz3bUAfjScps+zNCm8ddoG3iPIicOS0vdExu0FZDxabIeSCKpEd9A9zyt2qw6rxH80YiqLxLx9jcIKABkF9pKNrAeGO2aVrTui8nOkVkVN6H8mTNcMheDg8w7pFciQA04k+11wLkUh9hPhk6O1lI+uVXGXTDhPmLEbQ==
  template:
    metadata:
      creationTimestamp: null
      name: hermes-webui-secret
      namespace: hermes-webui