apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hermes-webui-secret
  namespace: hermes-webui
spec:
  encryptedData:
    HERMES_WEBUI_PASSWORD: AgCSdJw4lSDVLP8d4zN80tHwt//VtKZlulK0CxI/jJzI3ev3g7lSnMFsonWCpcM2J1407+ARzZGdBc3JY/hnPuBtdCxicj1U8HnXrSCpJ6IdXSrWuwKs3yYSkvcY6BL3Qx9A/NQkFO517Qz+/yz/7xbmC/CcJnMOb4GP3nTJj+pcu8BeR87auaQrglW8vgdBOsAWt/vp7jPlit8qREG/n+wq6IuYkZ3nna03I82YWKw4OC4GuVBSSAovOY3Clhz8f3twGbD9kkxXTj08mGfidV1O/xio3qC1qWpc7/Z9ph6B13i+/wH8edFWCj/OGdEHeMtalghJkhqCLsH6DrXVSSOWRBeehe26zK9j+H/pFosOzQj+UdntrQNqaw9zbY+/W1AgxMe4qnXHxpXU5grOLYpX4fB97JAIe2P8jx3S1XEKfdDU0rlWx7eAwOsRKPD91Noo0IGC37hrp8O2X57J067SHC5Vjupf1G3FjOYl1Bisxli74Ru0fUTYPiW/hE62ZlAXpch/O8LnxWk3kzMP5HfNKhTwrbyGLoo8vSNvs0XP8P5V6JfkSTAdNtRVODqoVoR7oY5ryRyK9H1pfT/2GPJ6XJ9QjsqPqDrIS+u7wVtUYWV9A9e4cc43VTqTqfCahsEMfji17ozyNnheqqQHEBBFiUmMPxMqgclabVuVb+AaAUHHqLy2Ww60EHGScAD3XV3GwxK5ZjUFv4cMw==
  template:
    metadata:
      creationTimestamp: null
      name: hermes-webui-secret
      namespace: hermes-webui