---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hermes-webui-secret
  namespace: hermes-webui
spec:
  encryptedData:
    HERMES_WEBUI_PASSWORD: AgCnEMi3PGlpPfiGHZB1VxmMSR9HS97Bsp86+X8S4/XxJrddT/Zms8V2dHhNkkxs+xWeFQgWjrN/yxrphtKLaSOrqVNuqu5XoJwx3RWQ4s+e5j/zYKIAxzC2SYkXMqGiTt986YkOFroKsaFuKXJ4szk8fSYUrFwPyGepn+DVs6riW3Fbd2Xyw+yNQGcRSLss7H1VJhRLJexmDZfl9alVHZU060aWNhULC/5QINw7baEvpz/OKZzFPdfoHvwx3G18F0oq57iUsVOpYCDjIyBLaRbSfOLYRXFOY3VDJw2Pc8/e/wzk3HgmP0e2BnDFpQDwrKIGWVzNxPcMZeCA2ZdmpWhM8HUI+Va6jsHQXRn2J2py/LnrJknPmglsM6poJxZRn2eVb8VKfYHPxvHAJ2TxdtGCd0Xkexz4C7Bf2Apwu8ZGRwuqe/UbORtFnQmTLzuIAmXbZPwpmwyxgxBVppMXPOLIyby5IKsxLhEJkclQLYDWwtFcuZrrq53FZTBc+uXeR/MrCGt9vBMcKVCveEV04RY89BZXR9Hy1FsQNQoMQMydKtXJBHeoZUzZFpn5/d8gRqLXtIp8zzGpo6+jirAQtjpSQZ/5EhOgaCV2MEvmfLFt5POccAnXiW9lbDvr0S+Rdp5rPegxmCzlyjAzMfghWYxJaKREUlEye16RZi5RHHJORfHfAVxdhlSFewD7NQdKnQmncGziUGVpctprIw==
  template:
    metadata:
      creationTimestamp: null
      name: hermes-webui-secret
      namespace: hermes-webui
