apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: coral

resources:
  - namespace.yaml
  - configmap-test-script.yaml
  - pod-test-inference.yaml
  - job-test-inference.yaml
