apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: victoria-metrics-tls
  namespace: monitoring
  labels:
    app: victoria-metrics
spec:
  dnsNames:
    - monsv02.oostrandpark.com
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: victoria-metrics-tls
