apiVersion: v1
data:
  config.yml: "auth:\n  enabled: false\nbirdseye:\n  enabled: true\n  mode: objects\n\
    \  quality: 8\ncameras:\n  tapo_c210:\n    detect:\n      fps: 5\n      height:\
    \ 360\n      width: 640\n    enabled: true\n    ffmpeg:\n      inputs:\n     \
    \ - input_args: -rtsp_transport tcp\n        path: rtsp://frigateuser:str0ngP@ssw@192.168.68.134:554/stream2\n\
    \        roles:\n        - detect\n      - input_args: -rtsp_transport tcp\n \
    \       path: rtsp://frigateuser:str0ngP@ssw@192.168.68.134:554/stream1\n    \
    \    roles:\n        - record\ndetectors:\n  coral:\n    device: usb\n    type:\
    \ edgetpu\nlive:\n  quality: 8\nmodel:\n  height: 320\n  labelmap_path: /labelmap.txt\n\
    \  model_type: ssd\n  path: /edgetpu_model.tflite\n  width: 320\nmotion:\n  contour_area:\
    \ 100\n  delta_alpha: 0.2\n  frame_alpha: 0.2\n  frame_height: 100\n  mask: []\n\
    \  threshold: 25\nmqtt:\n  client_id: frigate\n  enabled: true\n  host: mqtt.mqtt.svc.cluster.local\n\
    \  password: '{FRIGATE_MQTT_PASSWORD}'\n  port: 1883\n  topic_prefix: frigate\n\
    \  user: '{FRIGATE_MQTT_USER}'\nrecord:\n  alerts:\n    post_capture: 5\n    pre_capture:\
    \ 5\n    retain:\n      days: 14\n      mode: active_objects\n  detections:\n\
    \    post_capture: 5\n    pre_capture: 5\n    retain:\n      days: 14\n      mode:\
    \ active_objects\n  enabled: true\n  retain:\n    days: 14\n    mode: motion\n\
    snapshots:\n  enabled: true\n  retain:\n    default: 14\nversion: 0.16-0\n"
kind: ConfigMap
metadata:
  name: frigate-config
  namespace: frigate
