apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: frigate

resources:
  - namespace.yaml
  - sealedsecret.yaml
  - sealedsecret-basicauth.yaml
  - configmap-config.yaml
  - tcp-proxy.yaml
  - pvc-media.yaml
  - deployment.yaml
  - service.yaml
  - middleware-basicauth.yaml
  - ingress.yaml
  - certificate.yaml
