---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: frigate-camera-creds
  namespace: frigate
spec:
  encryptedData:
    camera-password: AgChV4LUu8r54SrVBVsNxweNLsLVcgQrE5McQ8DSYKS1s+yt7ZG9rHanSa+suapGZloVeYbtRzWtq5GZpXePcTqc68akY7Fw1NSmZSD+MBcH6C6FdUSX1xunkfLLzK+aXtbFS5F6DK0jEf+u3OWpDlQnbRGWypN/d7kbvQiOA01ALVk8b59sEf18GDefXiBw8lhzzq/J5IZMu4xkwBIyyNqHV39SiDuzyVORXUWfuZcMMHtH9wwtsysDMd7ahx/Y2BBfItX9wne6x39lWul4bW+rUuJBrPBQOl+sfWJONmZTzd1URiwhHASFwPGzAFBXREl6uglJJOqVI6uWMeIRdU3qIvZVMxi3t4km+QTMbN9e9UlS+klIXPrDef9hoBmzr8jCQmMnQ/3tjT0k2xYsOezSHGLE1pH7l0+k/FLLAnYu6s2ZbKTCPC3P03Un+nApHbY9v3lw5nrBPpxpkI+2nNnMQc8l2Z55n7GUsddRgvfNv2ADnSzEfkwf/xxlZo/90l+9D/i+u+TfwitTN2DOe4iJRmM0wL3fSf0rj17yWDEO84TOSPyv2I4zq4ToHDQnT2cOHAYe0LAuhI0HGEEPlTbaVV4eweOmEAsHqXlE0b2RZL+01jK7jjpLAuUU/5U5diK+kccdKQ7jVqDP82BtyYo908iTXUPEf1Mmrlo99yJWGGoJgkaOESUuTurCPVwFgQzITteMNcOez/Q=
    camera-user: AgB0JpuMzH8d+z6g3nB2pIpxJpk4fQ6uLJYlgrvh57r1aUcxjLFK8Bb5cjg9xr+V4Y946ZVEpZb0DFDpSYDOVYjVAA7qnW80qVoY7R8Jrxk2RbTTo4xfLEN7z/e0CJixn6+Kl1zMXCbyKPO/LJXhxhBgArZLZEV+9v8E7pu4cGJjOZ7459LQusbwTrnoERbznCgexM4gKggug6A95BLIyAUY58XckdWVmT7zH2TW0rB6eyVM+lTs85j8HtRxLxWQ32AAajXPf+v5nXueqaqd/d5Kt5LntaxhxnirKPlZIGfHwCf70vB4MDHNeW74h80spqf1oGs8MbHiMrvaWQd8iM+gQVppzw42OsshgusfHvFTgmpGIQ6OJo/t4dj3FcGObB/UAPJMdG4fa+HIqPyfpEcF+0rdTcii9J9mD5Wdl3OYOIIxUm+5faABLGdz2/la6LWgEkMq+bzNnOwxNVrbRJms8IHguCdhcWrp5uWXALjF9lJjU+Di1gqcb7mIQ/Jm/7djU2O5h8QDcHPDuWYC2Sx48I+KLdclwZk/sosLcA8FaMC/+uweIDMyfLBRsS092dm0TfeNPD2I82c9A4kDyVl5lhEUzU7RBoNktNeJt2r0AgY5BamBL70O4grEBknYc8MsGD68MsmxiI8OBWU+mAmk3YIbNOAa8rWyb2iqT7KVZ0ULZfubC7AlYX2EB0jgAqTGn3gsbw==
  template:
    metadata:
      creationTimestamp: null
      name: frigate-camera-creds
      namespace: frigate
