---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: frigate-secrets
  namespace: frigate
spec:
  encryptedData:
    admin-password: AgChqt31znOhfygx5+EwOND86D//UCqktG0snwNzqmKnDLVCKr7dZaOB/re9rlER434Qkyv0VC0sGCRDKpclwwqwi6pippGxB2rTdhK1+yScK1Y/paiDQ59liJ5gQOJsHmLkQThk4e6LoMpDiODWVuF9g+bU8mI+IqxeJi//Ec+RCj8XlZ4lK3xMemOXLgaPoMyJnK0vhAG8FKMwJb0/tXObO0q5/L9Y7sI8anq8wu2k35U72KeOMMg1GdDHkm9Dyc+tKSgKMKn4HmvLF2tIyUsz9mjFsDBfwv/ZjnsFNFzqxQ9VXvjdF0w+5/dHXOs6LX+OMPNRRIwCslYtUpjzzj/GZ8HaNxppdTqyU0W9AYV9MrwHP6wfxFW4T05Sh8MXKHHkn277MV8udB6WJNVRpmNmWd9sq/NHMmwiTQX2w89uu1sC4sFL4oepHEuybrB2cczkqtlkd+Z+F+cWrgyTzDUTDEZSBgZmf0dQ4dbyllukMBph8wW1XyZtLw5oqlJ0sRd/8BWCcCeDUBBQHdGIVp2VyF9KNyppuWHfG1ARH+ytNbsI9bULlp1Yu8wSAIxgUaawg3wyN8rutJeomFfa7i/kfh+mVKusgY3xhk3mfQX78gFCySTRMmw2jYi3zkvokNUhOhEiBR2reoJJxdMbjji94KRGNXcn8ADVEBHKshV563qqyow6lBTue2H4Q9OkC9mXMW5HGDRFyDCACI9V9z10c8FUBC04WBg=
    mqtt-password: AgChxK+iZY1lgpxSa+ETk2dpbmsQia0Spcn1cifKyyVNnnFiy/48+1AMPBqMRJk2JUGUShgBmP+mYtLIZ4yYwK6G7sc6HKctKudl6oSHvOu/pNg6BE5Lz4TQxinSlgcdmTCc/dYIkSWbemyrlOyIcsL/wOwndpjY4aOEXdJcBrET1Mvhi0kaw05fbojzubA9W3ciFVAIQey0gIwsSVmjxpBLMdIQWtLdkLqwiDvRkUSQYC+wPsu824kCteSY94RWo5JEGHVsxDWMlPSjjyMWziKxioGj3qD40NBUHZHdAb/yz0vEGAzSCHYi/Kdu9KgqL18mpR/ga5+lZ73z5VbAhCHxuDJUmz8F1apqN7t41oC0j0Y8j1gOLygU+Xf0ycVY06Wgd+CxKwCSJe+vNt9UR6qS/fXzk2eumcTLOuemdw0qLlu/oe0RCW7+xd0MzzHHQtMnNl2dqGH5r8yY86rzsM4kS8sMH8Q7UjOmjTLl5NlDI/R/NWogpcvvclfb8MIvcSouec/HO8hae+epNbAEeZ6ohTUDG9aH7zqgOMZsbq1jejPjDjXpdB17bzQ2Kj5LoeO5I6uT+447rsBNBJfqQTC4AsNkXq0f7EHFDiODrfJ7PwTcGZd/jgrIOIQmIGbHXLauRtKMv+eGSuG3C7BJtq2YPirkY47toN2AWQpoStryBXaLvNqallyEE3ZzbBgL6/O0neXNx8IOlHmAdQ==
  template:
    metadata:
      creationTimestamp: null
      name: frigate-secrets
      namespace: frigate
    type: Opaque
