---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: frigate-basicauth
  namespace: frigate
spec:
  encryptedData:
    users: AgBx23Y6gZ0HytjltPW8IEU+WJw+rVKPk5J59c/HHNocCU0ebwrU8u1N9cUWqC35XZMAEIO9Yy9ddT637suwBp2oDuBF6G9sPDrOkxWY/UV48NPxjlu6XcJ+5RC7PsY9P0nyY29uwHbbD+lzQ6xvx1kkIKz5Attl5K0CSCUsJSl9AzyDk6QdDyUYMEMrbYPMhu3GsHNJ0osZU2fsLcYO5WDtt6uSc1+mkhxbDVMDN8careGrzRn6ANMx2LkNIKzcBNKl6UuPD8rqzIITAxwd1cMK/+PWsFTujCyJUmJbd3Nmij09z1Yd/kRUr6uMDwwkvKorUimseRN/MtQyQ1GsemCG6cF4/P7XMewCQOs0qyfFpfz8UdHWY2AjqmUTK7yNsldCf43Sf/u5NqyvIhotkscvxkwpIlfvoGB2IV0dbpsPNC8yo+EQC+HQ3JvG3d4IFfuZRSi+uqzLUhVCtoWhGaQUDNrwJAe50kKCzD5FRg0/xZ8ndmK904A/CgvRqmDIKILrmc9iLRFZx3bQ7qaYRXw6ghbpAd6DCkr8ye+/ZjiZwuw4Y0ypm55r+sN6DtZcyJQXb6pBltPq+gikeQGie7oNyLLwnV8ECJ9oqr0Y8BKk0wFYkZN1YGqaASQKxViNy69hXb7h8ZNqQJP8Si3RB7mAWnHgrgnc+3j14Lu4JmfmGtAR7YXoNDjhIM8EVpahQTCSP2hakC+B6jdTP8y/one+3vjXwtnnAMwUVEUoitegfu9+qk92DRtXmgq5GM0TQvJgfWLWAqazESwHYr9fqaQtZ34l2A==
  template:
    metadata:
      creationTimestamp: null
      name: frigate-basicauth
      namespace: frigate
