---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: frigate-basicauth
  namespace: frigate
spec:
  encryptedData:
    users: AgB6kWz8yW3n3DIiWcqnipoIMmKxa9K3ps0yQEBgckRiy1sEgf1EgsJGJBMUpe0DchzkskyHE/l7Us/vTlw4b+UBvpRch+Y+16FeVz41b26iCTVvjko1qmARAa5xNcxR9Np91vMHZgdfWe4ryqIrcpOE/dov9jdrNvtWvzft4DXXgAZN2L5lKHoa2s0C0ZFz4KHl5lMRn0rh4+1WElV25QtB7wxASXSICPv1m8P4hERsIWzDL1jmdrzDL78hmtm7dDI56dJ0EShrWpMOoGtQrp8goaACjJhDSsPHCA2ltdVxSlDvTGZ0UoRZ4gQ4jkBexiG0eLqPaEG7RTPgIDdVXJaFz8qrC5fjy5H3IlcOzElMYmrHREmUi6XzWtpOs+9r9p1Lwx81lz7Xb+iUgzmy+NUpmtJSvVFectbUFf65YZ5s/A538SOoefGDjhhRuxTpNXve6Up0roVF3FdXLf65a48Spb4vM8ORyaW6LGotKM4YRufsFYCbLfasrY5jNwdh0NkrymT0gS7nYzglyqjPhQz/nWexj35isOB6sZQBujwrv8UGq21iJjJpEGyxq9iTbZ3RCV/oPYeHWzxOw3mdU8xeP7W2rZ8LBbrJKVQUCJHlm2l+JkitcVQ1J7KHZ4BS20UAclXjrzqUJL5dfpRbZ2nPG+qTDXgbdJadQ4mL7MBN7X/MvUxSX8XUNn5CLnqs1THxL/YO/sJ/sT39p57a5hFbDkiEY+LPKV35k+Ve68D1qh72jQ1x5cwy1WgEJBzKgV0hh2X3pQDyjwKRzSV35bxY4f8=
  template:
    metadata:
      creationTimestamp: null
      name: frigate-basicauth
      namespace: frigate
