---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: frigate-basicauth
  namespace: frigate
spec:
  encryptedData:
    users: AgAiZSn8jzG/9MJmAHj4KGoISJOcG4tAyNPhrDoHQC01FVlU/8HOLq9lN5dgGNSHeM5ixL8fWFx1XyUAkUtN9smrFjFn9hqj4TP2m7mvHzhoL4O4/2JMWiQKv7hEVEwuV0yp+809sDlsEUzuNadt81EeokZw8fcGS4QEhwis8GGuo8sc4n7sYznR137HuvX7YBXlWvx7ZyE8cXC638tehTRQPtKRLLXflk3Qj5V2w8MQkHpFcevYUnDQa3MMae+fsC5efiD5zUnpuud/MkpAgJSfRiM5FShHLdqr+bHfz2+2pE669ijWdsMoKrV+ew5y8FT3k2b8IjuJWeIZ9Njb9WLLe/MFyb+M4+E0JKgN79XcsHXZOv6H5iqS0gCEDOt9S8/TSeY8jKKbnYlqBwIWUel5egvMmKd0zstAzDApu2usuPm3yYqmw2QVcNtm+oiTN11VFufTE9e+8Y29Ta90J4rvfszTaBZNgxHcJ1aL6f/gvx6I1Y/5Q/30I+gEhtpSvFGMw25QAIkqQWDZe6IFX87zTLgo7gqsGXe5ZMbqLGVmdxB8S5d6pGoifkHGHJ7EXlK2YOacEv/BTWRK4+jO4HLb+6kXI+zT6bU4VaAYmJFJd1AEgEmi9qEjxL0raOWZ/dpuYqDeaqxFdcwjwE0Ge9tKCwBdz/YZPo9E1oVxy1Xrv/V/BhW9yLFxFwwwd/zvWgOMeVQYKw75rlhtzAwtPifyhehbHhqX8A5S0RySFqYY1OfEXy1GzyUlp631exhTyniyTY6NUVoZBBLLKsqLOCg2udM=
  template:
    metadata:
      creationTimestamp: null
      name: frigate-basicauth
      namespace: frigate
