---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: frigate-secrets
  namespace: frigate
spec:
  encryptedData:
    admin-password: AgChqt31znOhfygx5+EwOND86D//UCqktG0snwNzqmKnDLVCKr7dZaOB/re9rlER434Qkyv0VC0sGCRDKpclwwqwi6pippGxB2rTdhK1+yScK1Y/paiDQ59liJ5gQOJsHmLkQThk4e6LoMpDiODWVuF9g+bU8mI+IqxeJi//Ec+RCj8XlZ4lK3xMemOXLgaPoMyJnK0vhAG8FKMwJb0/tXObO0q5/L9Y7sI8anq8wu2k35U72KeOMMg1GdDHkm9Dyc+tKSgKMKn4HmvLF2tIyUsz9mjFsDBfwv/ZjnsFNFzqxQ9VXvjdF0w+5/dHXOs6LX+OMPNRRIwCslYtUpjzzj/GZ8HaNxppdTqyU0W9AYV9MrwHP6wfxFW4T05Sh8MXKHHkn277MV8udB6WJNVRpmNmWd9sq/NHMmwiTQX2w89uu1sC4sFL4oepHEuybrB2cczkqtlkd+Z+F+cWrgyTzDUTDEZSBgZmf0dQ4dbyllukMBph8wW1XyZtLw5oqlJ0sRd/8BWCcCeDUBBQHdGIVp2VyF9KNyppuWHfG1ARH+ytNbsI9bULlp1Yu8wSAIxgUaawg3wyN8rutJeomFfa7i/kfh+mVKusgY3xhk3mfQX78gFCySTRMmw2jYi3zkvokNUhOhEiBR2reoJJxdMbjji94KRGNXcn8ADVEBHKshV563qqyow6lBTue2H4Q9OkC9mXMW5HGDRFyDCACI9V9z10c8FUBC04WBg=
    mqtt-password: AgCAJQMPI8Z96HHFxe59h3YwhN3Su3wIBl8nx92TIyGp9B6sWdmhQIJNXrWTkykVbQZaK/3pzBWswzOrlllzbwN8U6HNJp/9M5tQUYc7Ht3kJ64TqmAJ5iUiV2imlVrqlIla4vyQdres2kvulLD9aMfBfqxdDKJ5vkP+zYkbwTHmyguTkB8lRr8omaLUQmZw4Qi6jW/tlA7PpBaoIntwHnvNUmHpttc1WmlLo9q8bN6iKBPbUq5bE8jFrZr9s+whbvLGYgY1gAKvcqViKZAOh7W6jOtBnlMFgR7FfeRPjEYfHyXixp7YslvawZ4IzSo2PGGDLbtHUqxBtqPedvRBhqqT4nFqRhh3G+SQL3RznZZhE8m8qqup40dR+FeO0gzq0B+ivDef61MCiaMytyGs8GoIHRGDcpmo6Z+JOCZz2/gh406MNmhGm7ZZN1ms9o4qcjTxyWI+az55FQUCSBvOb1MH710M+vpNXy6FFN+s6mXeK6G+AKUXTVJhwEMxCu7VaU3AWCn8ruiOi1qpB1phdhU2IZco7z8R8mCQ8X564b39VLgGxOzQhcT17y3a6vALGdhZIojoWSIkRoVo0vqg/63dDgiKSSOAzTzw2FZXtBrmCNxPu/hsz3OGvnsGQUOilIJ4Op7JznnBfWpJe7bQ0lafb/L6V6Pwf0LyndrTfQ5zd6JKseb5w+HedLfqc4jipxlMM2zimq/CrOPgBYRS4+CUa+vB3g2k8j0=
  template:
    metadata:
      creationTimestamp: null
      name: frigate-secrets
      namespace: frigate
