apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hermes-workspace-tls
  namespace: hermes-workspace
spec:
  dnsNames:
    - hermes.oostrandpark.com
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: hermes-workspace-tls
