apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hermes-workspace

resources:
  - namespace.yaml
  - deployment.yaml
  - svc.yaml
  - sealedsecret.yaml
  - certificate.yaml
  - ingress.yaml
