apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hermes-workspace-secret
  namespace: hermes-workspace
spec:
  encryptedData:
    HERMES_API_TOKEN: AgC0qDD6HS0rXuNnA4DpmXBssxlPeqxMYep98flDI+eeYRAbsCpqOqIRSAgHK3FbSUeCiCqoYirjMOsnKdqWB06Tjl5XQST9gMec9V+iGwioalPI2MKoa0gic0mkq9Uvd3xURExaPQsuGJxSvgmA7SVGui/2yiaTFzCx6cM1wTyOHVn+6jtS51EiFLsr1OrbXKXiv75On3CdL3jFeEzbUKTPFoXFWWSrJuL+vcTEJPGbvoATi9PAneIvSZdqi3kcNirN7Oetfkf+Qs7NAa95J3T8204Wo79EAxogZG54gDCwpTjBuFZUaxzRAq7k8XJ6/89ZSi8XbNC/DWxy8nvp34/mtVS74DX4Yb37gs3n6Gqb+HnWgVEIo6kNPDWUk/WO4pTDD2IMsRXFeoS6vMgVrUZ/j14IQ4r/gAVnfxO+Niqgzfvyfau9TwylsqdPEoWwkLsH62I4GZzNZdicTatZhmpkxsdSaiYadMYQgGeBg+/lQLJ3LCkaWm2vMGGVz9FD6su00IC4Uc4DUQhgZTKKAxwVArYACV7119/vfY0zBjdk9UA33V883L2Ahnn3go0QF0AQwi3QTZdACo7zdoV00JI/sNNz0h7dkbyvziUJvToVVSgaWESuDzq15dPvLiE6LtrboFUJ7KkxVRl6tODasUY4j71PSYWJ7jjjdPRRy9XurNiMaGPyOj4Q0BZ7YlUZGyPYbi8kSEHI+nl4BVtMks3GqVcmr/s+YnJlaUkHniuFW6GRWPQnWvyiobxx+J5gRtKO8rWB5fhqVNdWcYObAmXh
    HERMES_PASSWORD: AgBUQut9J0LJyoxA+pbvMlrsvkeJ/9Y8HBOog4Faknk2dhkUT2NjtxidoopDWyIT/2y9/sAsfz5v+D0HsLo37zh1p3hp+zkq1xv8UvWiSPs1PjVtbNf1Hx4GBG75ioStp978EeKCJIuz5zLznbau9pvX7GYAmmzecmuZ7ob8LxU0BMwHgB8TfPGcJQSU3bL53Ar08/cqUtrFlXiEJR7MP/iCqNLaaqGLhyEvx9ED3OOBBxTwbIIJH7kDEIE4uEXlOVJMKTYMfuMVv3gqyPOKRvSTsRPUEgBrv+NBd7JS9T3FEL81oQGxpVastgkpewR0B1EGJaTsM9iLrQyFxrCxyQap9jnfLU0kPnxmcud7RFFbkYcMHF7W6qPZS/uhmMvcSdnJEUmEbPLJ+kzsJ/jOmusOzWiCNHOrhGfrsuSQHwHujRn9r80OLWHyyhBtsUBlpEDDv4gd335n6okq2D/aGj/caX3IiSFmWY2b0rEOLWwgt2HElMF5GDzXMOsYrgssPsiXar2yxzGJvSIoNtNr/FOkN7vTo+PLMmMFgQoL0NOLjwKyBaUjrV99L4Z1YbxCtE8Y5hm4ELig6MUjbMs8P1Hkyb4x1aerv0iwvs2TfZrVkgVUFZnB0MvskS6LB/L9jQXkGMOEhOob6nv/lcgWkwW+V1tvEioAmO+cpmi0UEh+jk1yw7R/GIag02MP3EF75zvxQ4qlBtyR/ixRKQ==
  template:
    metadata:
      creationTimestamp: null
      name: hermes-workspace-secret
      namespace: hermes-workspace
    type: Opaque
