---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: earnfm-restart
  namespace: earnfm
spec:
  schedule: "0 */6 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: earnfm-restart
          containers:
          - name: kubectl
            image: bitnami/kubectl:latest
            command:
            - sh
            - -c
            - kubectl rollout restart deployment earnfm-client -n earnfm
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                - ALL
              runAsNonRoot: true
              seccompProfile:
                type: RuntimeDefault
          restartPolicy: OnFailure
          securityContext:
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
