---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: earnfm-restart
  namespace: earnfm
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: earnfm-restart
  namespace: earnfm
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: earnfm-restart
  namespace: earnfm
subjects:
- kind: ServiceAccount
  name: earnfm-restart
  namespace: earnfm
roleRef:
  kind: Role
  name: earnfm-restart
  apiGroup: rbac.authorization.k8s.io
