---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: earnfm-client
  namespace: earnfm
spec:
  encryptedData:
    EARNFM_TOKEN: AgAQQMIWhHe1pEvaga3etN9w5NKU5QtcLwlawHq2O8ebKdxVBdUh5w5GmL6QYLG64afK+6QKGqavjpRebBEwVVfXm4+OlmB5iS9kjxf0OXkyJeutYCEbUhLCHaHOxTT21MZiUtbyB3vDJmTQ0VTG3+mQ0mpPLUEHyXfrcOoPuIa3JlyAnvilUHQXmf0P72EIV4s4CAP4fEN3OmN029Gan4eJTDGwoRx3rdDpim4RPhS2FPTIH0tIITSQRSwHaG36Db0C8+SH1YgX1+a1OuwSfXk1e/++t80FvnhgRW6x8dfhAWH5w1uz8KGTOiKEGDS6EhHvKhB28+obFfCIv5CILwCb8b+iMpJEBhYB2hHbbdY9z/ZqODEf6N2FH6T118yslvuBWkNXqD29hfXKsZcYoPi5dqg9sB1/OIPUKId5kt22s/J1md6l1zkLuhLICdBC53aN6P6nVDLb3XlOzgmPY2UT0HdjZzr7C4FNEamHxwa+ih7P0aZ7gARB5GFydpX0AAgjNkexje+slotsGFl2n1XkH2RHyqPdDIFX0tVDznwyG10sOZteVr9+o+i/XAbOqiJ3Z9JyO89wSIadhIytGJbb++kZggTdStSxz5TkeV9wcuybfKc6OGp9hMvVTWncZMnXTmGjn3XnpvRVaHiIbVdoyQ5R+EBWbW2EAoBrLcEibi2CpD0jy1Po5goaP2sTjWDtsYsDQkKM3vtdx7SztdCFYxiHbEX5gKbc/YeLTuPhJ4vFdBA=
  template:
    metadata:
      name: earnfm-client
      namespace: earnfm
    type: Opaque
