---
apiVersion: v1
kind: Service
metadata:
  name: myst
  namespace: myst
spec:
  selector:
    app: myst
  ports:
  - name: webui
    port: 4449
    targetPort: 4449
    protocol: TCP
  type: ClusterIP
