apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: headlamp
    repo: https://kubernetes-sigs.github.io/headlamp
    version: "0.33.0"
    releaseName: headlamp
    namespace: headlamp
    valuesInline:
      ingress:
        enabled: false
      service:
        type: ClusterIP
        port: 80

namespace: headlamp

resources:
  - certificate.yaml
  - ingress.yaml
