---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: headlamp-oidc-secret
  namespace: headlamp
spec:
  encryptedData:
    client-secret: AgCBaWxXoQ3e/nCjHupXVSzy/Xp+2N+asGY7hCaQZgU58DnnCPPAOs2sHOk0KN25/oRPubWpqWy4HOzXBo5bHCo85hUFry9ax2pN3xD+9/KCma1WA08+fyLt8IHLzffZj+kkAZrtudi+I3jui8WYETSnjehz2HsV93j2pYN9yLDSVfzJNCy4W6mcV+UGWzKBgunBevtlSnB6HxSGIQR9IbVPAL0PbCsZmX0RF1HqR6JfGdj7p1xSIr1l13hKbw4R52FQVl5pT9roc8iPQgDwAeCiPvkThE6/y4zoh+H7nl8cHbAEBl+GQ4aTJ3kOrH+nUCn29NjYTWv06k6WoK8cLd+5KyERByfZXF6krmXyiKvsDcNJ3Gy77Y149iTL1p6VWzMzmncSCYaU7MVnltc/rxQQy09ZuS7sXETtacowuzsRG1d/s1bWqpiRnXDvci0heX+7Rm2D45JsCkLVgVYW1f+MJipmG9gcH0KwTHOWqkDYNzZWERKJus4altMhHDMh1+1b2KlNULOGCUeSfXLO4e1DdEUSuQOnmBq/Hrhk1Rzto5pyQsARFPxuDpnGvydvg9gLiVUY9h8y0H8Nh/Vry6ZMi/5dLm3k/Xw+tWMO2l503WbmYD2GSyoMzEUpkqiojJJOvvB/cUOr5RsrIMQU/eUUWsRmtGqw1laGQKqQr8Ia+ZI4yKJ2+3n8O7LbBvyc1CeRP2qGEqJ6oNx3h7Luj+jgT0w3yG8iKYFTPbupmgjxRO+tXDak/0dzKMZsOE3uqAJGHKrsyrvGtmswRWXrds8YZZYaLcLKXmnNJhwKGf0AyMTzp5sazmUZs8iZX4LyCZzlP1o/uPhJE/Qf2u3tyDhtd1Eiq33aOWk1Iy87MzrnTg==
  template:
    metadata:
      creationTimestamp: null
      name: headlamp-oidc-secret
      namespace: headlamp
    type: Opaque
