apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://vmware-tanzu.github.io/helm-charts
    targetRevision: 9.1.3
    chart: velero
    helm:
      releaseName: velero
      values: |
        configuration:
          provider: nfs
          backupStorageLocation:
            - name: default
              provider: velero.io/nfs
              bucket: /volume1/k8sv2/backups/velero
              config:
                nfsServer: 192.168.1.2
          volumeSnapshotLocation:
            - name: default
              provider: velero.io/nfs
        credentials:
          useSecret: false
        initContainers:
          - name: velero-plugin-for-nfs
            image: velero/velero-plugin-for-nfs:v0.5.0
            volumeMounts:
              - mountPath: /target
                name: plugins
        persistence:
          enabled: true
          size: 10Gi
          storageClass: nfs
          accessModes:
            - ReadWriteMany
        tolerations: []
        nodeSelector: {}
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        backupsEnabled: true
        deployRestic: true
        restic:
          podVolumeBackups:
            enabled: true
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi
        kubectl:
          image:
            registry: docker.io
            repository: bitnami/kubectl
            tag: latest
  destination:
    server: https://kubernetes.default.svc
    namespace: velero
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
