apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero-ui
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/RKruit/k3s-gitops
    targetRevision: main
    path: base/velero-ui
  destination:
    server: https://kubernetes.default.svc
    namespace: velero-ui
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
