apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - argocd-install/install.yaml
  - argocd-app-nfs-provisioner.yaml
  - argocd-app-netdata.yaml
  - argocd-app-n8n.yaml
  - argocd-app-uptime-kuma.yaml
  - argocd-app-sealed-secrets.yaml
  - argocd-app-velero.yaml
  - argocd-app-cert-manager.yaml
  - argocd-app-sv02-traefik.yaml
  - argocd-app-sv02-n8n.yaml
  - argocd-app-sv02-uptime-kuma.yaml
