apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
patches:
  - path: argocd-install/insecure-patch.yaml
    target:
      kind: Deployment
      name: argocd-server
resources:
  - argocd-install/install.yaml
  - argocd-app-openbao.yaml
  - argocd-app-monitoring.yaml
  - argocd-app-nfs-provisioner.yaml
  - argocd-app-bootstrap.yaml
