apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: xwiki

resources:
  - namespace.yaml
  - sealedsecret.yaml
  - postgres-statefulset.yaml
  - pg-service.yaml
  - xwiki-deployment.yaml
  - xwiki-service.yaml
  - xwiki-pvc.yaml
  - ingress.yaml
  - certificate.yaml
