---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: xwiki-postgres-secret
  namespace: xwiki
spec:
  encryptedData:
    password: AgCX0MJfUStXfn/R2ocqNH7Y1QDux9LkHtTljU7a9eI58fLiezTKZFRR93Qg9H2tx5XsJjCBQkajfWQgOwB4VtLeFW0QgydoOw5awiS739pMfL5cvm6m9a6ymgGZ3JvQ+glq+EhN6WWDj+tSfD0xzoJ0ckzSKPtcWMMjknyZJIJYzWpgQPxTlkXgSKv5c8kgM49vcVNsdrth49RbcPWpMb5Ni/z4k2V/UPF8X7ZU/em49qzir1cJBUjFMeahnNKr9kd88nkuLtfSPJwACs5YXdSLsNVq4wsLLgkL/KWRCf8NncYGYph/6Q4yyr6bnUtn3DCLkT4bgTZRCnNoeYjdNGYDfjCYO2mZlQusiedhkCnvxCNpdpiCsvUwoWSde4tibU8UiWV4dsFQZgLXXE1sxN+sEDgye1OZvsGZQ3CRi5TlH+1/yO9WsQIQV9yE1t74uKYn7rhhrnsXffNKlOnE01F92abFi5JEoiv0J1qOFhK3J44KVicfLqu/fEXf8a7prKo3bEy2jixLz8hIEIEEaaRIi2uGaRr8N6X5hSbU35asnel6kD5DLW7aXh2cRiyG8oueOL1Qpdxxobd+u8Wx0UL+ZjUf51CEV5REkzCMoxcy0o7uxLtNpETEetFaAf/iL++/QT8YsyztlRIbVWaJB/hUZV1BrOBzHNeDR6ZxLzeS9NomoiHuM4jApMAXq5mDnu8cwZCAJFtrFAglDVFy0S6DBlSifT/Qb4GZmjZmtHWDpg==
    username: AgAZATqjQx2jOmjIu4ja22jmv5z4aYHutvOmOuXhP5+UJTo96V29Au52rIMr7wNwjgMmTOHawKvOUZcYzf5W0E/sSBdjak4b2Pwxu8d4PZqkzGyMRLb+D0PHJuMXOuoYJWMKxI11J/eh5gZTHfG0s3iP9C/AID8cHniyvlTa6CnZI7R0FW1k3jM5XSKIEvzQAyRmcvDz6AhYxxwBy5C8o2wsso4SW6r6tdBKoY48NE3h2uWr8Dhoz5+fCrLgmEG1bmzaIhQTcX3r/qSrVJ4qsnMTt/eVfqcQkC9BpOFjg0mgP5rI0pZXJgFuKmOycOF+WuyArHQ1DfAzYue78DKOM95MrTCeSsn4IkvfwlODMYLBiXj/pklZaLhVmMAZrzf99jDoA1FZfFEh827KIVjdb+Qn9dKMg0r2JqZvKHpHRMlug/KXa9tYnMDXq8iw+K2y7MhezRpgaa/kZMp0TNRWprwSJKkcQpsU+Ospo4D4y6+u8uxY9O0+DvsYs9zAnSbGYvjytZW8Nkl/aWQc7ympi65XTBQM5DlWRlPiFxxmWPOwwAIqe9Eznt9Sdjbe1qS3L8xQsDVhLfrAi1R1LPbAQjNrw7i6+SdnXG4/TmUERkIT0+b+sxxTZdS3pLxhiS97cyEFhdOg1eThXzdzGjW7IHtn+jV/OtAo2FuuYFl7Cz/XvpfH/Y4ePvht0oXjsrhVZkj3TpAP7MA==
  template:
    metadata:
      creationTimestamp: null
      name: xwiki-postgres-secret
      namespace: xwiki
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: xwiki-config-secret
  namespace: xwiki
spec:
  encryptedData:
    admin-password: AgCDfno+YL6zKQasQgyeopP7WScTCCkKWQYgwVsZRaO8PznqjM/qic604x6rS66VwTXdUm2ikhcz1ji5hCTHwYBZshRy5jSrqYQofpflLhdpIXA4zil3l5Vv3HpfcLu2u0FTT8Yq2E3jY6eKeG57nEqzygs2gSlT7C8Ja8z4hOpRW0QE3vasBlv3CLf5Mv1Cor5Wt/QJTTeKeQWc+JmE5DGE360g9VXPGMbAZzR6IHACh9w+7AC2KTspo93UuvRrJSRI0n8h8VPCasDDptCdYP+rTrU8uFqH3qx3Ez8oEH/VMoBk2xnhiGIJNCusY6BjTZUb8rB6BtXXb5c2Ng6SVzmuwQio3bJ9puj4Qu4ISlGR1nOpV7RXNCUXR+yvJh7T8GW7yGX260SI4Hxbj/QdJOWYOW1hOpROQNsOTNqFqHtRRHfNUUXIHCaW4KcwVwJ/9zGXs2zNe+ZDiNmPux+LwIUNbaC9NJesaQPIlza8KKcY7fX5tQIMgN7EBM0tmXsZyCxqG+HtVPeAtaji6OzW9XOZ2ymf8I01/F/FJiIN+4naRFf/wdlPoowdC6i1fQ483xFNE2TOCkxklCmEeEM044v/BsehiaMLSdT7DnO1MIRxN/y+Jkjbq+49etz7Jtb5/f3ixIuPy5Dsu5LavdoMJ4qa3f6n1YNBhqKPujACmzdm6Y+E8g9w/aFyHvS+pM8gktzpx7CGHIoayxDLn5anMl2kXYCGTe5jSQ4=
  template:
    metadata:
      creationTimestamp: null
      name: xwiki-config-secret
      namespace: xwiki
    type: Opaque
