---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: xwiki-postgres-secret
  namespace: xwiki
spec:
  encryptedData:
    password: AgA8MXK9+N+QXDq8IPldTM8168X3p8fnxD1VnQOoDMHF2MbYUmqyZtN59tocX+l3E3kHXodt2qruacjehtCDAbLiICOAA5TRZN1/YxTdmyTGg1ihE4lfKId0m5LIGK7r7rrFzQTQetx5W5XSSEqsx9b9LgVvc8VUhy4MUWToLhPV0m0M3phMlIEZZmpp+oYWHFYC8lya9SoApkoKxSjI+hmlLw0qtvliLKwYDnipE1Jni/HKFH5gGj5uCvthKsBceXa+FVLpM2TF3WFCJBUM7iCoxBM8XMUDcd4M4+IbAI07ps9Xhp6o0ynkNTPE91FZEgN/otAUiirX/K0a902MuUBHsIOn1Z+gRB+9o5MS6/Ynvtl6HYUfFXKgLHX5LisUkOQDStP7Jf6+389rqi2INDRobKhAXPD+giF695rEQlXvncIWVJJLqVETTD9q5j0Pnz0aCJCgL1H9+FRO6Lzfs3jYi4r5Nr3Ag8jQ0n3eDA3WzKN3cm0Ct8YZ97I0AkhT1CKoMX196x2PIqegs9zvSnBJiDb4l7ycDXBqoNKUFUMf6PKx58UELqnwltJ/WzEa+AUbAuBHrMZ5Moa/e8rzbqkyV9yTDom3UiLeXnQGuwWqLcbjPWY1+h0lfQgEHX4csXBevfz2OmjookUqkYiY64feWYWltVw27h4EYpqxSaNA6dWEaf3XjSZrt5bQxwl23e2h4WN03x83jwK6jEBUtxuNkZBNS21erhel2ASDwF+1pg==
    username: AgBoQzkFSa++JS+9fBXsj1S8ICHr090C5Sw4o1id5UqetD9jlisHsqxfMNpER0nF+2gIX/qbUDnv94BNCiYYZwO3B3eHbkBKYHtWya5KzxseAKqW4zifv+gh7Az3rMRRyXwEYaiPHmOAyS5lQ+zEHya3e4e0tVdYCMNL1srlnSLWjhwF5v8ytQYOTuHAXnyeIRU9+5M7p1xmwTC8TB0ZigZBSoS4o0qIeg0eYslHDE1e+fzaljhNwF7D2zOCZgTHiTzrm9RFwzH7/Ys5oqmy+AHr8af7VQKvd9eSPx6i15sUJy7BKOu/tsWUhN7lEO7eTH1wxcz7bv3BaQ08qSHsH+xXBtsm12sWM6khwKGnr6XAIj05FxEzRFuurfwfJ4q7YyiyIDEzUjYUEgvdiDHohz4rq8Zhc09aaOHfE1kiE8X0DUw45EMTzNd6oHpboz4F67OGrsZv6Z52zlrQgoVeEoF6Mqtme31xfZ2CRkKUcH5qkYwkmbyGBLjvhS1AdMDGroNvYxBxPwkCB4o+31PmQlcfsAsOmixfyR6hBSujzsJ4Rr6FkzmLJ/le/b50x1ZbnJCJ/qQX7c8zZ3sLgXf5F46s/tvlCKrQXTBP/+6JYX3XpAfqMbsNu2ECq6EfXDLUcCKf1X2n3AYDh0fSV71Pw9OPYOzvD8TFS3Bn918a/nM11/5ZHQnxCf1I87+9coNSdf/Vz3RP3Q==
  template:
    metadata:
      creationTimestamp: null
      name: xwiki-postgres-secret
      namespace: xwiki
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: xwiki-config-secret
  namespace: xwiki
spec:
  encryptedData:
    admin-password: AgAvjFnr9614TRvFD3u1UHNDLwt3lVAqA6Gk4ETuVD5aJxUBZOZhNEwBq6kHNsyZtkGNU5m2fOgW2i5MpRI0i+cWtKBaqhrrPhJWhJT0SY3iDvb+4Ac9fCCizF1LPuIMRpEvyZO190lADnT2J+QvUDEEvLDt0DCmQcUY+erXc86zQHS0LQs1n596O+CDBXB0O+DUBZSo/etjKC9mdHOuasj0sbQImepC4DV4mdoFY1FsHraSxrgvlbC2Jh9YwfuLCnHbMgPWs6GDIB700SPwPQbMoD7nY1HfpgkA38gYFfYh2UfA+3uv3UaPDIw02Rb7htE1EzuUQTO3kccCdgFkjA0svM+Iv8fMD1gFZu+vlV1zFv6tuCvvz0YausuV61EMgsZz/ypoAjXouXQMDmSgJrGuCxe6BKrtX+ib5BBY9P0Nu0vOxE/RgABkvas1hzEgGHNyg82kfXhNj9Az1JaY0AEjLEZlh/0u1HBDi7X0Lb6Aqr6GcqH1yTL+1yhfJfjSdeMScRTbE5ZPFuoKd8ZbGt91ZmfScwNWKVJiat6czuz/NuLBMzytD1S3Y7B4z5HP5aLVWkTgeKpAEYffUA0BXwqaETgXrja5VDYdRMhC1cCd/9nXNi9IDayFgiHzNBk8Sl5JpjCvZtw2GnhtyUXpZ8d/CXf3gYLX4/xSCvLQ0VYPlJOaOVzikC3cN9vzhqXpZlbi36Of2pMMcvcU+j3HKmcJBZtf04nCloI=
  template:
    metadata:
      creationTimestamp: null
      name: xwiki-config-secret
      namespace: xwiki
    type: Opaque
