---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argocd-oidc-client
  namespace: argocd
spec:
  encryptedData:
    clientSecret: AgC1UDVPdtmTNn9HJvwjCYafjwJR3M+Xon2ZaCGkKME88Z8QlZj3BVIxh79jl6Bxc+AvWEUUSad8xllmu9Q6STA69pPe+gY2vZ45aqzan4GtolBV1ckP1zMyCyb26Ui9qDQdVQZwbnxoIMM6rUgSmCuJIoNmYG1DEqrmnDt2m9I+w6pT7ofNRTxGFeDkYA2M5vvSWw+IX/+lRm3ERh4P4ynPrpmEd0NK9bJ+BKx66zycGCpJJg79wiQgdX+4GRUoDpinGAqz0iCPf8UL54IQAGURoGPoKlERYEH7a2BNwNiDndMEolwJFNfY0e4QyTe2pHqXStDnZMCzpdGtpLWDUAN/leqKeuVxEEa32iDZKiwQE1bMsMBJHZ2OqIhf/0ppfQMV6qBI2yQLILkWvHUJ9SiCLhYO78KBtGeQKxhmT2tsXbCEVdQWYePKXTNbLu0kjSpm1hnfl1tBF4yw+qslCkYik7ajqfsl+roIFMFuXvw3uIbOrJ6vNyIzKyNrsIqx83F0iSi9kcfrXgTSDJu3gOwRvnKSIBVwocaaEITQkMNBW1Of4IPpo8YdwRnBZ2GN4IUkYGtfp+1ejpo2I1ZTuefiTTaPL742Jp3xNs+3c+HjkGafcMWtzybFxy8d3vCBJrDesHNmj7LWkCehJrjV81f5nU4fX3dmnWfnwcdB6UToeNTqQut+eG+WNWaTZnuyf/jbX9lj0cT+oqWmBP6N0yc4l+VWJssoMEfiyboHlz5wtLe+cx+Lr61+nIZXL9ajxd5wI4rtSwnYZ9kQrmgmnCnBv19i4K9CfD+y7OUAXXKGFA/hJoVo+y8iFbYxeExRT82Y9Lb5jKLqEgyfv7aczTacvqggX0s+z7VPThlD8P5bcg==
  template:
    metadata:
      creationTimestamp: null
      name: argocd-oidc-client
      namespace: argocd
    type: Opaque
