apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - install.yaml
patches:
  # Add insecure mode for server
  - path: insecure-patch.yaml
    target:
      kind: Deployment
      name: argocd-server
  # Add custom Ingress health check
  - path: ingress-healthcheck-patch.yaml
    target:
      kind: ConfigMap
      name: argocd-cm
