---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: homepage-argocd-key
  namespace: homepage
spec:
  encryptedData:
    key: AgAfm9nZYJavdKAo6DEDWAmNEGsP8nSmY9ndLr9TjSNIPUl74pZsTPo+9w/Vm7F+0D7nknhunAHqr7VhN0k7d+fe1eGeaHNuftMxjA77DV3H2lzcV1FL8XLqKNIffhdWkFZ/H5socj46LnFdz8hu1zNGs4mdKyEfrSeY1cKC+U2NFYRTcUuDoX2V2/GaVoZiAhk+p7icx8jIm+yVWL6SSbCgsk59kGRPTIoZbsleN4rDJ1TmEgaGB4dfblAPjWWR7LaHebnIjDB0xYqZLeH9EXnNXc+WFeWrth7lG47s2mnOyNu/t+jJjMIXwndhOSREMWd1GlxX/Lw129XMBG7XihMBv6aw+r+kWE8tUgNWixzuJWd1Ho2PJnL8kZ7P8dB5NKO6urYrmIQFcxfadKpuKudmuMMD7pJl2ThjVkpK8LlId0YwCr2huqVnnqsNZqR2UL1efVXdb4D7+ygOYH9s3vSSC+WyeHFhinkLXnVxZH13p/tku6KPkReURFkIv+gqHcsidlUN7pJ/z2RoYtF2lOS2n+mYewBKQwlqFl5J7resJosHi3ZGmjj77qoU0huyYK+IooPBv2duPKm2dBVPxM9HdNgBQthVRwAyWVWhduLj92yAeQ3K/hGkjFLS3bLDR7QiaAdwNPUZECw4jUuCBv0wsUa4YPg9bhq4dt2t6fpKbXl06Tesdn4ujhjUgbKSwUEtOaho3HWBGhGGhbPGRYHm2gkc7kgSlLPYivjBhJz4AHVa8Zfylc4eHg0S9AFEbUXhWfUK5Sx1tkgpO1qiJsLR4ELJ+K3RrX1a7T6Bk32xVRYqGrCH7C0hKSY1nNQa6Rk9/tqrBRaY3HPy37eUUV6SI+dYnuV3QVNE8vctvm1Fm7Tjl1y2Zua7q/yv8IiKsSo/Da0BGUx0cg1Zbe+v+EtMGb/DOfbwGzkUbLWhTOmobWzitdbt+ug5EPw/2eR2dVq0mMHyYgYNmV7doMqIUlBChcHj8Isl4KTewuUWK3Bd/B+c9erXWKHHlh2klzBw2iQ=
  template:
    metadata:
      creationTimestamp: null
      name: homepage-argocd-key
      namespace: homepage
