apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: victoria-metrics
  namespace: monitoring
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.io/ingress-backend: traefik.io/v1alpha1
spec:
  ingressClassName: traefik
  rules:
    - host: monsv01.oostrandpark.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: victoria-metrics
                port:
                  number: 8428
  tls:
    - hosts:
        - monsv01.oostrandpark.com
      secretName: victoria-metrics-tls
