apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - configmap.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - service-nodeexporter.yaml
  - daemonset.yaml
  - certificate.yaml
  - ingress.yaml
  - dashboard-configmap.yaml
  - dashboard-deployment.yaml
  - dashboard-service.yaml
  - dashboard-certificate.yaml
  - dashboard-ingress.yaml
