---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traffmonetizer-client
  namespace: traffmonetizer
spec:
  encryptedData:
    TOKEN: AgBNjcEeJr2hbhVNbJEErglwZbOWmFuWh6MOd1lasW0QNbod/j8fryDCcUsTtfVQVgHQrpMHgioF5m9SNse9sEBCnZxI8P5SFFkRlCmbPAGWW8rwBa9l89aO95+SBzJZH/oFxQNSPqbAFn0lRjhep29cpTiqId0N1AXbRDAtpur8HIula/0hnlK4FoxVGmsScjzAm9Nr7UA0VT2X4w3ONBrce2Iu3CalLdeV1OGPahR3Te8wWBRhHq38jee3tmUWarZixN4/kkoVhpiVM9BMAoGEU0NE99MD4HXakH8UPcqnqiBoLf+b7ICJNczdolM9r53aL7+AR8ukKNQXqW5e5QjbFkd8dPks88VyjBLTuH/WlqW+oVwZnE3W5tDfqruTj9qOqowOutfUKCpjL25VnqOyCnbQF29c2eoXqZPom2AK0WXHZ0NtB9DHu3kW216gyDnS1MaH6KJynRTndSJmTR/kQdCwEf+k65SXouohfi3pJnYXWPjKDmxyMu5iVxZOOwhBGsXx2YERFVORMAoYQHPNeKHy2H6Md1lOj3Un+WSVbxh15nKDGpEbLi2lFUsa9pVaGM0Dj7JzYzWz08WCYHnuUC2TdXxOD2TL0u7IGwr1su4acjfLvh4FfcyldGJV8ZHjrlRayP0R5wnV2d+T9rpQQbFFeZMayaTvCuxvIG7qRTp9mGFPepzLxSbLzxVdpu1jFHKEDaGkABv72fi7fOo7EmO3Ci6ekxgi0diZGg2EV4dUx65qy2GMotWyPg==
  template:
    metadata:
      creationTimestamp: null
      name: traffmonetizer-client
      namespace: traffmonetizer
