---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: repocket-credentials
  namespace: repocket
spec:
  encryptedData:
    RP_API_KEY: AgAVybZ0zvDJ2LOfr5tk1gt38KUXoZTTD18Rw3ktfmzKqLa3s95o7Kgyl1g/zrSYvwpEnOPin4eEizDmRoV+Mwe1R3+7RFJ+ifyHe9KEGAm2YYk7ZDzxJ9j2qRQldJiHM3BWuLTEUNJ7hGIrgpA64oSrIlWyi+8WkyhmOwpe9DeHpgIDR3YqWp/GDQKLZLhyrDQOf+51W5I2x7G8Sm3cnV3o9b8iu5XfqhF9AUDcz801YDq3fDBH80kym/jUrptHPp4fYt9w9+7IdkhDdM3x/W5ndgS0fNzKagkqsWeslzORINH7N0Diko4AjFgfAnEKnNO9Gc42Du+ugwHXc/b/s+Sd6uqdvX/rxK8CKS08DWipim9pcqpM0ZOG7O6OxPYxVxymE2++4YrnZC7p1L8UGWkUAeX+FxLd96eV9auKf1S44aC3XVLckepTKcpUk1S0W2W1XNTRs9YBUOy0EHNIoiU3+byfFvhW6eyGfZ9R4nq2+FbQqrDBIgKM3xQj9bm3VqmtBjVmelDoMZkuponERSJ3oNDfp1Cb/LLKgEq/0ZaQRa6MMgMaAuyhf3ioroagQSdV4wEU18NgvCSH5vxdFrnOYMq971z31aM3dQYBg6J6MCkYShZHT8FW4T3t112aOOYMLJ7zcDl/enzC0GHWtdNknMCfEOU07Ef3KtBWJw3MyEAt/41R7V4ZHNKEJJDeJfCECCEMqqK++AqALlzJpED+Hh/8P76O5jAroZBU1+VmPbQsAOI=
    RP_EMAIL: AgA0cs/aOtRoH+TQg37j0u6plU8RtXFzlx8UbrcxDdZtRQblX0O/P4K1bUAKC6g8kTyAkT/Fv8oDg8U0ncePc6tRAKcaIcW0aviWvOyxZO/cCxLbJLzaYJVHdw0E2Z/DdRK0Jb5Hyq3Gq1fPhnFBWzVo8RkVzfZeI41iC9pSL2Lja3uXvftvb18yscAF33FNqEEaefywjmsWX6Q3JIQTjN1W8EESBoEMsEJWzWeKvUdWKx0bPeifgJUrqLiX9XG6wKr3Ljg8Eah/+ukAao0VPbba/+Ij0hWEAO6/IqYTKpXLoVfi9/7hkKPmuunkNcFlMh36SFRARhpXSbzjsM9Nu/e1h8OzkalMGrSDCNyJ2TVgQ41Yk135SuWx8QvDmaAfDk1p/4K+BTCGfKqb50HptOkQ7XYx4+7cKAzGeB4AUDhVoy3uvq72WZrhxzVkj1dLdaTtoe78b3ghiYUHy295JLAJ/r81PikyKxo61yxmkipR39lo7TYcgM+8cZElixVbDDrneTwypoPOdDlzXI9qOAeMdx5PP8kncA/CyL0C+a9itqYJoVQjKAQLJy9HcOSpOPa0qMhouPPaX9uIkhhMXySGM+2o50r+vobC1ZHHkG1PL+QAX4dzzcpMhAf8EBf+/45xXUJwfyMmg5O1O6ALrZ6+gp91koO7K47VbDZ2HTShWQIpWVC5rZuZEZog7nQ4ze9Kc08IFkrYW5pdtNeeVKTU
  template:
    metadata:
      creationTimestamp: null
      name: repocket-credentials
      namespace: repocket
