---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-secrets
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBj6LUbf+rXlYQtYhI8xCDwzwSMJ3mYbkKoMdeTnt3prQg0vTf7TEO+0YSaVFSLMiZNhTn1QRiyB7yviVHYcNLTTW4XxxvPbnGPqUo1goneOpcLUsqva0Hj0u6QTM3ibXZIG/1UZoqUX5rSuVR2Om1fbawadu/2VKTnvolWFvUFjjSIrcJ6ktAhVaVLGIEnUJ4LH1ANFDDgGd84Z/6/LTSIZPwjYLiIYHIHpyPzFdtkkAGzFi6aACkcDbl2JcXmwlkvYIXqXxqT6PhxGaYGSrr/ZaoMCrHT9+Z/pAaXvXMxaR8D8IT7KaTslLNlLl5lAWbzS02uLKTOIPLtZhrqxrlrD9OM7yWFM1ATDtSkdS+A91V9E8KVuN/nXcHdaJClR+kFw9uMthffPccDq2NUIijP2j9AIFMtr8g+sSvJUtOIGt+Hwm/lhP1kSDbPVlU6IWt2JuFbSggi2KWUTNaP3K3PB78t25hBQDeDz6IMEq+RiRsqKkd3bn7w35+IfT4Iv8+PCnivgdc8K+b0c0CFS5EtgJs5MxG+gCrIKUFNSlFv1Rd2ISmoaM5TyJIBa6ttGJ+HYcENr5yzw0ju09mSpUVQczAO1Ajfwo7jfYYdl8IbfCU9ZDnM8BLyBceT8BGkdkl385NE9N1vP8x3ADabKUfKlxBCtncDfeSE1O8XTfPJaRXxHBSCYwndcI1apQeVHKMQEzZM7U8zaoGOeT5FCMMiJF2hvQ==
    admin-user: AgAatFxWJmGkv9DLdQyOZe+e1nAF7s5es8GYrQZOkZsZMTathBnZH6JbH2sw/gmTsT//YE4XbGAx3r7QKp5xJCA80742XUemW/4pM/yAXqcBwBozCITImcpS0mwDc911EUMio3BlSa43aAHI2pCYV7tqrjXw0z1YhXcxsGhXOFfkZktWJsRIOS+u5VTVTLMhxgQ3+OtwlFdCHHOm2Rcretzy+BXL4MzY9OHVv7Y0PG3nIaXlZwg7pDEE581+/j7A6LT3P3KxUef7yGdTxIu/MYw7+82g60PPVqvyU81WC3P8FSPYtk51hKc8iMgRzu9eEeChC7RiQJviY8JW6V9XyAW8TVpyN8TI7ccacTN1Hq0y0g03ldN2xCPhIHSrSYRcohvNBE1ndo2ZKP+d9jPxWPkHhXaldFLOxRlmEkIZ1/3MW/6jLPJbjQLhMP7mZmw2eKodKxS+pcFPS65Ll4sYPMB77fvQKsWeR6M5gL+I9QCbfvAfPFEDd8sRJ+m14vJu0RYwHqdo+qfjq8qd7TW1MC35hHJ4VKHtaSqVxPuiZIcJTMBQI4Npgb1w4+sVm731fCoRu24noSmgav2F8hEuoQrVqom4C9GBZLned31wATG1eDb/Lvj0309zE+o5Q3vZg3dKtnH/IdWKyoDuIK1jiUUTtywnj/H4NL4mWm4TS0Bm8r/fZiGFtdhZO0H96/Af+cz4FXNIiw==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-secrets
      namespace: monitoring
    type: Opaque
