apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - traefik/traefik-app.yaml
  - cert-manager/cert-manager-app.yaml
  - sealed-secrets/sealed-secrets-app.yaml
  - uptime-kuma/uptime-kuma-app.yaml
