apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: anna-tls
  namespace: anna
spec:
  dnsNames:
    - anna.oostrandpark.com
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: anna-tls
