apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-app-data
  namespace: todo-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
  storageClassName: local-path